site_name: loggr.io
pages:
- Home: 'index.md'
- User Guide: 'user-guide.md'
- Developer Guide:
  - 'H5VZR': 'developer-guide/h5vzr.md'
  - 'API': 'developer-guide/api.md'
  - 'raspi': 'developer-guide/raspi.md'
