site_name: loggr.io
pages:
- Home: 'index.md'
- User Guide:
  - 'Standard': 'user-guide/standard.md'
  - 'Pro': 'user-guide/pro.md'
- Developer Guide:
  - 'H5VZR': 'developer-guide/h5vzr.md'
  - 'API': 'developer-guide/api.md'
  - 'RASPI': 'developer-guide/raspi.md'
theme: mkdocs
